#include "localization.h"

const char* SelectText(Language language, const char* chinese, const char* english) {
    return language == Language::English ? english : chinese;
}

const UiStrings& GetUiStrings(Language language) {
    static constexpr UiStrings chinese{
        "HEIC → PNG / JPG 批量转换",
        "文件",
        "退出",
        "设置",
        "语言",
        "关于",
        "关于 HeicConverter",
        "HeicConverter 用于将 HEIC 图片批量转换为 PNG 或 JPG，并可保留 EXIF 元数据。",
        "它支持多线程转换、PNG 压缩设置以及基于 EXIF 拍摄时间的自定义文件名。",
        "libheif 解码 · libpng / libjpeg-turbo 导出",
        "使用的开源库",
        "关闭",
        "转换",
        "文件命名",
        "日志",
        L"选择包含 HEIC 文件的文件夹",
        "请选择文件夹",
        "浏览…",
        "搜索子目录",
        "保留 EXIF 元数据",
        "转换成功后删除原 HEIC",
        "覆盖已有目标文件",
        "输出格式:",
        "PNG（无损、支持透明）",
        "JPG（体积较小）",
        "压缩级别 %d",
        "质量 %d",
        "并行线程:",
        "%d 个线程",
        "（检测到 %u 个逻辑处理器）",
        "开始转换",
        "正在停止…",
        "取消",
        "状态: %s",
        "成功 %zu    失败 %zu    跳过 %zu    活跃线程 %zu / %zu",
        "当前: %s",
        "提示：只有目标图片成功写入后才会删除原文件；JPG 不支持透明通道。",
        "失败:",
        "任务失败:",
        "跳过:",
        "扫描警告:",
        "启用 EXIF 自定义文件名",
        "使用模板组合自定义文字、EXIF 拍摄时间和序号。",
        "自定义文字:",
        "例如：旅行、家庭、项目名称",
        "文件名模板:",
        "例如：{text}_{datetime}_{seq}",
        "添加 {text}",
        "添加 {datetime}",
        "添加 {seq}",
        "恢复默认",
        "序号起始值:",
        "序号位数:",
        "占位符：{text} 自定义文字 · {datetime} EXIF 时间（YYYYMMDD_HHMMSS）· {seq} 序号",
        "没有有效 EXIF 拍摄时间时，将保留原文件名。建议模板包含 {seq}，避免连拍照片重名。",
        "预览: %s",
        "模板错误: %s",
    };
    static constexpr UiStrings english{
        "HEIC → PNG / JPG Batch Converter",
        "File",
        "Exit",
        "Settings",
        "Language",
        "About",
        "About HeicConverter",
        "HeicConverter batch-converts HEIC images to PNG or JPG while optionally preserving EXIF metadata.",
        "It supports multithreaded conversion, PNG compression settings, and custom filenames based on EXIF capture time.",
        "Decoded by libheif · Exported by libpng / libjpeg-turbo",
        "Open-source libraries",
        "Close",
        "Conversion",
        "File naming",
        "Log",
        L"Select a folder containing HEIC files",
        "Select a folder",
        "Browse...",
        "Search subfolders",
        "Preserve EXIF metadata",
        "Delete original HEIC files after conversion",
        "Overwrite existing output files",
        "Output format:",
        "PNG (lossless, supports transparency)",
        "JPG (smaller files)",
        "Compression %d",
        "Quality %d",
        "Parallelism:",
        "%d threads",
        "(%u logical processors detected)",
        "Start conversion",
        "Stopping...",
        "Cancel",
        "Status: %s",
        "Succeeded %zu    Failed %zu    Skipped %zu    Active threads %zu / %zu",
        "Current: %s",
        "Note: Original files are deleted only after output succeeds; JPG does not support transparency.",
        "Failed:",
        "Task failed:",
        "Skipped:",
        "Scan warning:",
        "Enable custom EXIF filenames",
        "Combine custom text, the EXIF capture time, and a sequence in a template.",
        "Custom text:",
        "For example: Travel, Family, Project",
        "Filename template:",
        "For example: {text}_{datetime}_{seq}",
        "Add {text}",
        "Add {datetime}",
        "Add {seq}",
        "Reset",
        "Sequence start:",
        "Sequence digits:",
        "Tokens: {text} custom text · {datetime} EXIF time (YYYYMMDD_HHMMSS) · {seq} sequence",
        "Files without a valid EXIF capture time keep their original names. Include {seq} to avoid burst-photo collisions.",
        "Preview: %s",
        "Template error: %s",
    };
    return language == Language::English ? english : chinese;
}
